### ISSUE TITLE
WHITEBOARD

### ISSUE THREAD

**Issue by Splunki** [Paranormalcow/Startpage#3]
AN OMNIPOTENT THINGMAJIG THAT PICTURES,TEXT , LINKS AND OTHER AWESOME THINGS CAN BE POSTED ON BY OTHER USERS OF THE START PAGE.
-GREAT FOR REMINDERS
-SHARING REPOSTED CONTENT
-MEMES
-DANK MEMES
-NOT BLACK
-VIDEOS
-TORRENTS?!
-FUN

**Comment by Paranormalcow** [comment]
I recommend you take a sitdown there bud.
